version: '3'
services:
  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"  # production ke liye 80 port rakho
    restart: always

  backend:
    build: ./server
    container_name: backend
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - ./Server/.env
    depends_on:
      - frontend